export const taskContents = [
  {
    id: 1,
    name: 'Sign In',
    describe: 'Log in reward, one $Matter for each day',
  },
  {
    id: 10,
    name: 'Report bad content',
    describe: 'Successfully reported %count% time today',
    count: 1,
  },
  {
    id: 11,
    name: 'Report bad content',
    describe: 'Successfully reported %count% times today',
    count: 2,
  },
  {
    id: 12,
    name: 'Report bad content',
    describe: 'Successfully reported %count% times today',
    count: 3,
  },
  {
    id: 13,
    name: 'Report bad content',
    describe: 'Successfully reported %count% times today',
    count: 4,
  },
  {
    id: 14,
    name: 'Report bad content',
    describe: 'Successfully reported %count% times today',
    count: 5,
  },
  {
    id: 15,
    name: 'Spend %count% $TIME',
    describe: 'Spend %count% $Time in Metatime',
    count: 600,
  },
  {
    id: 16,
    name: 'Spend %count% $TIME',
    describe: 'Spend %count% $Time in Metatime',
    count: 1200,
  },
  {
    id: 17,
    name: 'Spend %count% $TIME',
    describe: 'Spend %count% $Time in Metatime',
    count: 1800,
  },
  {
    id: 18,
    name: 'Spend %count% $TIME',
    describe: 'Spend %count% $Time in Metatime',
    count: 2400,
  },
  {
    id: 19,
    name: 'Spend %count% $TIME',
    describe: 'Spend %count% $Time in Metatime',
    count: 3000,
  },
  {
    id: 20,
    name: 'Spend %count% $TIME',
    describe: 'Spend %count% $Time in Metatime',
    count: 3600,
  },
  {
    id: 21,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 600,
  },
  {
    id: 22,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 2400,
  },
  {
    id: 23,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 4800,
  },
  {
    id: 24,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 7200,
  },
  {
    id: 25,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 9600,
  },
  {
    id: 26,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 12000,
  },
  {
    id: 27,
    name: 'Invite friends',
    describe: 'Successfully invited %count% friend today',
    count: 1,
  },
  {
    id: 28,
    name: 'Invite friends',
    describe: 'Successfully invited %count% friends today',
    count: 2,
  },
  {
    id: 29,
    name: 'Invite friends',
    describe: 'Successfully invited %count% friends today',
    count: 3,
  },
  {
    id: 30,
    name: 'Invite friends',
    describe: 'Successfully invited %count% friends today',
    count: 4,
  },
  {
    id: 31,
    name: 'Invite friends',
    describe: 'Successfully invited %count% friends today',
    count: 5,
  },
  {
    id: 32,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 600,
  },
  {
    id: 33,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 2400,
  },
  {
    id: 34,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 4800,
  },
  {
    id: 35,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 7200,
  },
  {
    id: 36,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 9600,
  },
  {
    id: 37,
    name: 'One content has been read for %count% seconds',
    describe: 'Read articles in Metatime for %count% seconds',
    count: 12000,
  },
];
