import React from "react";
import { ImageProps } from "pancake-uikit";
export declare const HomeIcon: React.FC<ImageProps>;
export declare const TradeIcon: React.FC<ImageProps>;
export declare const LiquidityIcon: React.FC<ImageProps>;
export declare const FarmIcon: React.FC<ImageProps>;
export declare const MarketIcon: React.FC<ImageProps>;
export declare const MiningIcon: React.FC<ImageProps>;
export declare const IfoIcon: React.FC<ImageProps>;
export declare const MemberIcon: React.FC<ImageProps>;
export declare const AssetsIcon: React.FC<ImageProps>;
export declare const MallIcon: React.FC<ImageProps>;
export declare const CoinIcon: React.FC<ImageProps>;
export declare const CardIcon: React.FC<ImageProps>;
export declare const NestIcon: React.FC<ImageProps>;
export declare const AirIcon: React.FC<ImageProps>;
export declare const BuyBountyIcon: React.FC<ImageProps>;
export declare const DocsIcon: React.FC<ImageProps>;
export declare const GithubIcon: React.FC<ImageProps>;
export declare const InfoIcon: React.FC<ImageProps>;
export declare const MoreIcon: React.FC<ImageProps>;
export declare const ReportIcon: React.FC<ImageProps>;
export declare const PoolsIcon: React.FC<ImageProps>;
export declare const MediumIcon: React.FC<ImageProps>;
export declare const TwitterIcon: React.FC<ImageProps>;
export declare const TelegramIcon: React.FC<ImageProps>;
